AWSTemplateFormatVersion: 2010-09-09

#---- Inicio da sess達o DESCRIPTION-----#
Description: Workshop Cloudformation - 200 - Setup feito via Web Console

#---- Inicio da sess達o PARAMETERS-----#
Parameters:
  EnvType:
    Description: Environment type.
    Default: prod
    Type: String

#---- Inicio da sess達o RESOURSES-----#
Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-005f9685cb30f234b
      InstanceType: t3a.micro
      IamInstanceProfile: "ssm-role"
      Tags:
        - Key: Name
          Value: exemple3
        - Key: Owner
          Value: Workshop

      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          sudo amazon-linux-extras install nginx1
          yum install nginx -y
          systemctl start nginx
          systemctl enable nginx
          echo "Workshop Cloudformation 200" > /usr/share/nginx/html/index.html
          systemctl restart nginx   


  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [workshop-sg, !Ref EnvType]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


#---- Inicio da sess達o OUTPUTS-----#
Outputs:
  outputInstance:
    Description: A reference to the created EC2 Instance
    Value: !Ref WebAppInstance  